appName: myhelmapp

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'Welcome to NGINX on ROSA! By Venkatesh'

image:
  name: eyesoncloud/webapp
  tag: 47

secret:
  name: nginx-secret
  appKey: MySecretKey123

serviceAccount:
  name: nginx-sa

role:
  name: nginx-role

roleBinding:
  name: nginx-rolebinding

pvc:
  name: nginx-pvc
  storage: 5Gi
